version: 0.2
env:
  secrets-manager:
    github_oauth_token: "github_oauth_token:token"
phases:
  install:
    commands:
      - "cd /usr/bin"
      - "curl -s -qL -o terraform.zip https://releases.hashicorp.com/terraform/0.13.4/terraform_0.13.4_linux_amd64.zip"
      - "unzip -o terraform.zip"
  build:
    commands:
      - cd "$CODEBUILD_SRC_DIR/infra"
      - terraform init -input=false 
      - terraform plan -var aws_region=eu-west-1 -var github_oauth_token=$github_oauth_token
      - terraform apply -auto-approve -var aws_region=eu-west-1 -var github_oauth_token=$github_oauth_token
      - aws s3 cp src/ s3://technicaljones.net --recursive
      
artifacts:
  files:
    - src/