version: 0.2

phases:
  install:
    commands:
      - "cd /usr/bin"
      - "curl -s -qL -o terraform.zip https://releases.hashicorp.com/terraform/0.13.4/terraform_0.13.4_linux_amd64.zip"
      - "unzip -o terraform.zip"
  build:
    commands:
      - cd "$CODEBUILD_SRC_DIR/infra"
      - terraform init
      - terraform plan
      - terraform apply -auto-approve -input=false
  deploy:
    commands:
      - aws s3 cp src/ s3://technicaljones.net --recursive
artifacts:
  files:
    - src/